# Generated by Django 4.1.7 on 25623-03-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=256)),
                ("device_name", models.CharField(max_length=256)),
                ("device_type", models.CharField(max_length=256)),
                ("device_status", models.CharField(max_length=256)),
                ("device_store_id", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Right",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("right_id", models.CharField(max_length=256)),
                ("right_name", models.CharField(max_length=256)),
                ("right_code", models.CharField(max_length=256)),
                ("right_description", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "权限表",
                "verbose_name_plural": "权限表",
                "db_table": "right",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role_id", models.CharField(max_length=256)),
                ("role_parent_id", models.CharField(max_length=256)),
                ("role_name", models.CharField(max_length=256)),
                ("role_code", models.CharField(max_length=256)),
                ("role_description", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "角色表",
                "verbose_name_plural": "角色表",
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_id", models.CharField(max_length=256)),
                ("sensor_name", models.CharField(max_length=256)),
                ("sensor_type", models.CharField(max_length=256)),
                ("sensor_status", models.CharField(max_length=256)),
                ("sensor_value", models.CharField(max_length=256)),
                ("sensor_device_id", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status_id", models.CharField(max_length=256)),
                ("status_name", models.CharField(max_length=256)),
                ("status_type", models.CharField(max_length=256)),
                ("status_smax", models.CharField(max_length=256)),
                ("status_smin", models.CharField(max_length=256)),
                ("status_desc", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("store_id", models.CharField(max_length=256)),
                ("store_name", models.CharField(max_length=256)),
                ("store_manager_id", models.CharField(max_length=256)),
                ("store_address", models.CharField(max_length=256)),
                ("store_address_code", models.CharField(max_length=256)),
                ("store_phone_num", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=256)),
                ("user_name", models.CharField(max_length=256)),
                ("user_password", models.CharField(max_length=256)),
                ("user_code", models.CharField(max_length=256)),
                ("user_account_name", models.CharField(max_length=256)),
                ("user_sex", models.CharField(max_length=256)),
                ("user_location", models.CharField(max_length=256)),
                ("user_phone_num", models.CharField(max_length=256)),
                ("user_contact_address", models.CharField(max_length=256)),
                ("user_contact_address_code", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role_id", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ssvorm.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色表",
                "db_table": "user_role",
            },
        ),
        migrations.CreateModel(
            name="RoleRight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("right_type", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "right_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ssvorm.right"
                    ),
                ),
                (
                    "role_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ssvorm.role"
                    ),
                ),
            ],
        ),
    ]
