# Generated by Django 4.1.7 on 25623-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0002_device_right_role_sensor_status_store_user_userrole_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alarm_id", models.CharField(max_length=32)),
                ("store_alarm_id", models.CharField(max_length=32)),
                ("device_alarm_id", models.CharField(max_length=32)),
                ("sensor_alarm_id", models.CharField(max_length=32)),
                ("alarm_desc", models.CharField(max_length=128)),
                ("alarm_status", models.CharField(max_length=256)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="status",
            name="status_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_manager_id",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=32),
        ),
    ]
