# Generated by Django 4.1.7 on 2023-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0005_alter_alarm_alarm_id_alter_alarm_alarm_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="user_alarm_id",
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
