# Generated by Django 4.1.7 on 2023-03-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0006_alarm_user_alarm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "store_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ssvorm.store"
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ssvorm.user"
                    ),
                ),
            ],
        ),
    ]
