# Generated by Django 4.1.7 on 2023-03-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0007_userstore"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserStore",
        ),
    ]
