# Generated by Django 4.1.7 on 2023-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssvorm", "0008_delete_userstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_status",
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
